name: NFTC Contracts Continuous Integration

on:
  push:
    branches: [ "main" ]
    # paths-ignore:
    #  - src/templates/sc/**
  pull_request:
    branches: [ "main" ]
    # paths-ignore:
    #   - src/templates/sc/**

env:
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Step
      uses: actions/checkout@v3
      
    - name: Use Node.js 16.14
      uses: actions/setup-node@v3
      with:
        node-version: '16.14'
        cache: 'npm'

    - name: Add .npmrc
      run: ./.github/workflows/npmrc.sh

    - name: Clean install
      run: npm ci

    - name: Build Contracts
      run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Step
      uses: actions/checkout@v3
      
    - name: Use Node.js 16.14
      uses: actions/setup-node@v3
      with:
        node-version: '16.14'
        cache: 'npm'

    - name: Add .npmrc
      run: ./.github/workflows/npmrc.sh

    - name: Clean install
      run: npm ci

    - name: Test Contracts
      run: npm run test